import type { DecisionDoc } from './types';

const revisitScale = ['A second host becomes operationally necessary.', 'Recovery objectives cannot be met with the current design.', 'Measured scale or availability requirements outweigh the added complexity.'];

export const decisions: DecisionDoc[] = [
  {
    id: '001', slug: 'cloudflare-tunnel-over-reverse-proxy', title: 'Use Cloudflare Tunnel instead of opening inbound ports',
    context: 'Multiple HTTP applications need stable public hostnames while the infrastructure remains on a residential network.',
    problem: 'Provide encrypted public ingress without router port forwarding, public origin addressing, or a separately managed reverse proxy.',
    alternatives: ['Nginx Proxy Manager with forwarded ports', 'Caddy or Traefik', 'A private VPN only'],
    rationale: 'A native cloudflared service creates outbound connections and maps hostnames directly to loopback-bound service ports. This keeps certificate and edge routing work outside the Docker estate.',
    tradeoffs: ['Cloudflare becomes part of the availability and trust boundary.', 'The tunnel alone does not provide application authorization.', 'Origin services still need careful local binding and access controls.'],
    consequences: ['No containerized reverse proxy is required.', 'Every public hostname is visible in one ingress map.', 'Cloudflare Access must be configured separately where identity enforcement is required.'],
    revisit: ['A provider-independent ingress layer becomes a priority.', 'Local-only or mesh-VPN access replaces public publishing.', 'Advanced origin routing requires a local proxy.']
  },
  {
    id: '002', slug: 'compose-over-kubernetes', title: 'Use Docker Compose instead of Kubernetes',
    context: 'The estate is a single Arch Linux host with independently maintained application directories.', problem: 'Choose an orchestration model that is understandable, recoverable, and proportionate to one node.',
    alternatives: ['Kubernetes or k3s', 'Docker Swarm', 'Native systemd services'], rationale: 'Compose preserves declarative service definitions without introducing a distributed control plane whose high-availability benefits cannot be realized on one node.',
    tradeoffs: ['No scheduler-driven failover or native rolling deployments.', 'Cross-project dependencies and shared networks require discipline.', 'Some operational work remains script-driven.'], consequences: ['Each application can be changed independently.', 'Compose files remain the primary deployment record.', 'Node failure remains a full-estate outage.'], revisit: revisitScale
  },
  {
    id: '003', slug: 'arch-linux-host', title: 'Use Arch Linux for the host', context: 'The system doubles as a learning environment and a continuously maintained personal infrastructure host.', problem: 'Select a Linux distribution that exposes system behavior clearly and provides current packages.', alternatives: ['Ubuntu Server LTS', 'Debian', 'Fedora Server'], rationale: 'Arch favors explicit configuration, a small base, current packages, and first-principles understanding of systemd, networking, storage, and container runtime behavior.', tradeoffs: ['Rolling updates require attentive maintenance.', 'There is less vendor-oriented long-term support.', 'Operational stability depends on disciplined upgrades.'], consequences: ['Host configuration knowledge is part of the system.', 'Updates should be staged and accompanied by recovery readiness.', 'The Arch Wiki is a primary operational reference.'], revisit: ['Maintenance effort becomes disproportionate.', 'A long support window becomes more important than package freshness.', 'The host becomes shared production infrastructure.']
  },
  {
    id: '004', slug: 'alloy-over-promtail', title: 'Use Grafana Alloy instead of Promtail', context: 'Docker, journald, and custom operation logs need one collector feeding Loki.', problem: 'Choose a supported collector that handles discovery, relabeling, file tailing, and system logs.', alternatives: ['Promtail', 'Fluent Bit', 'OpenTelemetry Collector'], rationale: 'Alloy supports the required Loki pipelines and represents Grafana’s current collector direction while Promtail is deprecated.', tradeoffs: ['River configuration has a learning curve.', 'The collector has broad read access to logs and Docker metadata.', 'Configuration mistakes can silently drop labels or streams.'], consequences: ['One component covers Docker, journald, and files.', 'Collector state is persisted.', 'The configuration graph can evolve toward metrics or OpenTelemetry later.'], revisit: ['OpenTelemetry becomes the estate-wide standard.', 'Collector overhead becomes measurable.', 'A simpler single-purpose shipper meets all requirements.']
  },
  {
    id: '005', slug: 'loki-over-elasticsearch', title: 'Use Loki instead of Elasticsearch', context: 'The main need is short-retention operational log search for a single host.', problem: 'Provide centralized logs without running a resource-heavy full-text search cluster.', alternatives: ['Elasticsearch', 'OpenSearch', 'Graylog'], rationale: 'Loki indexes bounded labels and stores log bodies economically, integrating directly with Alloy and Grafana.', tradeoffs: ['Free-form queries scan log chunks rather than a full-text index.', 'Label design strongly affects performance.', 'The single-node filesystem backend has no redundancy.'], consequences: ['Logs remain available for 48 hours.', 'Grafana is the primary query interface.', 'Logs are operational evidence, not the backup system.'], revisit: ['Long retention or compliance search is required.', 'Full-text analytics becomes a primary workload.', 'Multiple nodes justify object storage and distributed mode.']
  },
  {
    id: '006', slug: 'jellyfin-over-plex', title: 'Use Jellyfin instead of Plex', context: 'Local media should be streamed without relying on a proprietary account or paid server feature tier.', problem: 'Select a media server with broad clients, library management, and transcoding.', alternatives: ['Plex', 'Emby'], rationale: 'Jellyfin keeps server control, accounts, and the core feature set within the self-hosted environment.', tradeoffs: ['Client polish varies by platform.', 'Remote playback and transcoding require administrator tuning.', 'Metadata and plugin maintenance remain local responsibilities.'], consequences: ['Media remains readable directly from the filesystem.', 'Application accounts are managed locally.', 'Hardware transcoding is an optional future optimization.'], revisit: ['Required client support is unavailable.', 'Operational cost exceeds the value of local control.', 'A different server provides a necessary accessibility feature.']
  },
  {
    id: '007', slug: 'navidrome-over-plexamp', title: 'Use Navidrome instead of Plexamp', context: 'Music playback is a focused workload built around a local FLAC library.', problem: 'Serve music efficiently to web and mobile clients without coupling it to the video server.', alternatives: ['Plexamp', 'Airsonic-Advanced', 'Gonic'], rationale: 'Navidrome is lightweight, music-specific, and compatible with Subsonic clients while keeping the music mount read-only.', tradeoffs: ['It does not replace every discovery feature of commercial streaming services.', 'The SQLite database needs consistent backups.', 'Client experience depends on the selected Subsonic application.'], consequences: ['Music and video lifecycles are independent.', 'Hourly scans control library discovery.', 'The service can remain small even as the library grows.'], revisit: ['Library size exposes SQLite limitations.', 'A unified media experience becomes more important.', 'A required client is incompatible.']
  },
  {
    id: '008', slug: 'immich-over-google-photos', title: 'Use Immich instead of Google Photos as the primary library', context: 'Personal photos and videos are long-lived private data.', problem: 'Provide automatic mobile access, search, albums, and sharing while retaining control of originals and metadata.', alternatives: ['Google Photos', 'PhotoPrism', 'Nextcloud Memories'], rationale: 'Immich provides a modern client-server photo workflow while the asset library and database remain on owned storage.', tradeoffs: ['Backups, upgrades, and capacity planning become local responsibilities.', 'Machine-learning features consume additional resources.', 'The project evolves quickly and requires controlled releases.'], consequences: ['PostgreSQL and Valkey become critical dependencies.', 'Asset and database recovery must be designed together.', 'Machine learning can remain disabled until resources are available.'], revisit: ['Mobile reliability is insufficient.', 'Storage or backup cost becomes unsustainable.', 'A different self-hosted project offers safer migrations.']
  },
  {
    id: '009', slug: 'prometheus-over-datadog', title: 'Use Prometheus instead of Datadog', context: 'The observability target is a single self-hosted host and its containers.', problem: 'Collect infrastructure metrics and evaluate alerts without recurring ingestion fees or exporting telemetry to a SaaS platform.', alternatives: ['Datadog', 'Grafana Cloud', 'InfluxDB'], rationale: 'Prometheus matches exporter-native metrics, local control, PromQL alerts, and Grafana visualization.', tradeoffs: ['Storage, upgrades, and alert reliability are self-managed.', 'The current single instance has no high availability.', 'Configuration drift can disable expected rules.'], consequences: ['Metrics remain local.', 'Blackbox, node, and container metrics share one query model.', 'Persistent TSDB storage must be corrected and verified.'], revisit: ['Multiple sites require centralized managed observability.', 'Long retention becomes important.', 'Operational burden exceeds SaaS cost.']
  },
  {
    id: '010', slug: 'homepage-over-homarr', title: 'Use Homepage instead of Homarr', context: 'Operators need a compact service directory with health and application widgets.', problem: 'Choose a dashboard that is configuration-driven, fast, and easy to keep beside Compose files.', alternatives: ['Homarr', 'Dashy', 'A custom page'], rationale: 'Homepage provides YAML-defined groups and broad widgets without requiring a separate database-centric dashboard workflow.', tradeoffs: ['Widget credentials need careful secret handling.', 'Docker discovery creates a privileged metadata path.', 'Visual customization is intentionally limited.'], consequences: ['The dashboard configuration is reviewable as text.', 'Service links mirror the tunnel map.', 'A socket proxy is a future hardening opportunity.'], revisit: ['The dashboard becomes an interactive control plane.', 'Secret management remains awkward.', 'A custom portfolio-integrated operations view is built.']
  },
  {
    id: '011', slug: 'portainer-over-docker-desktop', title: 'Use Portainer instead of Docker Desktop on the server', context: 'The host is a headless Linux system administered remotely.', problem: 'Provide occasional graphical inspection without installing a workstation-focused runtime.', alternatives: ['Docker CLI only', 'Docker Desktop', 'Dockge'], rationale: 'Portainer connects to the native Docker Engine and adds browser-based inspection while Compose remains authoritative.', tradeoffs: ['Docker socket access is root-equivalent.', 'The management UI becomes a high-value security target.', 'UI-driven mutations can drift from files.'], consequences: ['Portainer is used primarily for inspection.', 'Repeatable changes stay in Compose.', 'Identity-aware access is strongly recommended.'], revisit: ['CLI-only operations prove sufficient.', 'A Compose-focused UI better matches the workflow.', 'Socket exposure cannot be adequately constrained.']
  },
  {
    id: '012', slug: 'single-shared-network', title: 'Use a shared homelab bridge network', context: 'Services live in separate Compose projects but selected applications must communicate by stable DNS names.', problem: 'Enable cross-project communication without addressing containers through host ports.', alternatives: ['One default network per Compose project', 'Multiple trust-zone networks', 'Host networking'], rationale: 'An external bridge named homelab gives every attached service consistent embedded DNS and avoids localhost assumptions.', tradeoffs: ['The network is a broad east-west trust zone.', 'Compromised containers can discover more peers.', 'Exceptions such as immich_default complicate the mental model.'], consequences: ['Prometheus can scrape exporters by name.', 'Media services call qBittorrent and peers by DNS.', 'Network membership must be documented as part of security review.'], revisit: ['Service count or exposure justifies segmented trust zones.', 'A compromised workload demonstrates lateral-movement risk.', 'A second host requires routed networking.']
  },
  {
    id: '013', slug: 'discord-alerts', title: 'Use Discord for operational alerts', context: 'Alerts and image-update notifications need a low-friction destination that is already checked regularly.', problem: 'Deliver actionable notifications without operating a mail relay or a dedicated paging platform.', alternatives: ['Email', 'Telegram', 'ntfy', 'PagerDuty'], rationale: 'Native Alertmanager and Diun Discord integrations make delivery simple and preserve rich message formatting.', tradeoffs: ['Webhook URLs are bearer secrets.', 'Discord availability and account access become dependencies.', 'It is not an escalation-management system.'], consequences: ['Firing and resolved alerts share an operations channel.', 'Webhook rotation is part of incident response.', 'Alert grouping controls noise.'], revisit: ['Alerts require acknowledgement or escalation.', 'Notification privacy requirements change.', 'A self-hosted notification service is introduced.']
  }
];

export const decisionBySlug = new Map(decisions.map((decision) => [decision.slug, decision]));
