import type { Provenance, TopicDoc } from './types';

function topic(
  slug: string,
  title: string,
  description: string,
  section: string,
  intro: string,
  items: string[],
  provenance: Provenance = 'verified',
  related: string[] = [],
  diagram?: string,
): TopicDoc {
  return {
    slug, title, description, section, intro, provenance, related, diagram,
    sections: [
      { title: 'How it works', body: description, items },
      { title: 'Operational notes', body: 'The statements on this page separate observed configuration from recommendations so future changes can be reviewed without rewriting history.', items: provenance === 'proposed' ? ['This material is a proposed runbook and is not evidence of a deployed control.'] : ['Configuration-backed facts are marked verified.', 'Upstream defaults are marked inferred.', 'Recommendations are marked proposed.'] },
    ],
  };
}

const overall = `flowchart TB
  Internet[Internet] --> CFDNS[Cloudflare DNS]
  CFDNS --> Tunnel[Cloudflare Tunnel]
  Tunnel --> Host[Arch Linux host]
  Host --> Docker[Docker Engine]
  Docker --> Network[homelab bridge 172.26.0.0/16]
  Network --> Apps[Application containers]
  Network --> Observe[Observability containers]
  Apps --> Storage[(Host filesystem)]
  Observe --> Storage`;

const monitoring = `flowchart LR
  Node[Node Exporter] --> Prom[Prometheus]
  Cad[cAdvisor] --> Prom
  Black[Blackbox Exporter] --> Prom
  Prom --> Rules[Alert rules]
  Rules --> AM[Alertmanager]
  AM --> Discord[Discord]
  Prom --> Grafana[Grafana]`;

const logging = `flowchart LR
  Docker[Docker logs] --> Alloy[Grafana Alloy]
  Journal[systemd journal] --> Alloy
  Files[Event and cleanup logs] --> Alloy
  Alloy --> Loki[Loki, 48h retention]
  Loki --> Explore[Grafana Explore]`;

const media = `flowchart LR
  Prowlarr --> Sonarr
  Prowlarr --> Radarr
  Sonarr --> qBittorrent
  Radarr --> qBittorrent
  qBittorrent --> Downloads[(downloads)]
  Downloads --> TV[(tv)]
  Downloads --> Movies[(movies)]
  TV --> Jellyfin
  Movies --> Jellyfin`;

const photo = `flowchart LR
  Users --> Tunnel[Cloudflare Tunnel]
  Tunnel --> Immich
  Immich --> Valkey
  Immich --> Postgres[(PostgreSQL)]
  Immich --> Assets[(Asset filesystem)]`;

const music = `flowchart LR
  Library[(Read-only music library)] --> Navidrome
  Navidrome --> Web[Web client]
  Navidrome --> Subsonic[Subsonic clients]`;

const network = `flowchart TB
  cloudflared[cloudflared on host] --> Loopback[127.0.0.1 published ports]
  Loopback --> Docker[Docker port publishing]
  Docker --> H[homelab bridge]
  H --> Media[Media services]
  H --> Ops[Operations services]
  H --> Obs[Observability services]
  Immich[Immich stack] --> I[immich_default]
  Immich --> H
  Homepage[Homepage] --> I
  Homepage --> H`;

export const topics: TopicDoc[] = [
  topic('homelab', 'Homelab', 'A configuration-backed map of the personal cloud infrastructure.', 'Homelab', 'This is operated as personal cloud infrastructure: a single Arch Linux host, independent Compose projects, shared service discovery, outbound Cloudflare ingress, and a local observability stack.', ['24 documented runtime and platform services', 'One stated homelab bridge subnet: 172.26.0.0/16', 'Native systemd cloudflared service', 'No containerized reverse proxy'], 'verified', ['homelab/architecture', 'homelab/services', 'homelab/security-model'], overall),
  topic('homelab/architecture', 'Architecture overview', 'The request, application, observability, and storage planes of the system.', 'Homelab', 'The architecture deliberately stays legible on one host. Each Compose project owns its lifecycle while the external homelab bridge supplies cross-project DNS.', ['Cloudflare terminates public edge traffic.', 'Host-published ports connect cloudflared to containers.', 'Containers use DNS names, not localhost, for east-west traffic.', 'Persistent state is bind-mounted to host storage.'], 'verified', ['homelab/docker-network', 'homelab/container-communication'], overall),
  topic('homelab/infrastructure', 'Host infrastructure', 'Arch Linux, Docker Engine, Compose, systemd, and host storage form the execution platform.', 'Homelab', 'The host is both the failure domain and the operating boundary. Container isolation improves packaging, but availability remains tied to one machine.', ['Arch Linux provides the host userland.', 'Docker Engine runs application containers.', 'Compose projects remain independently deployable.', 'cloudflared runs as a native systemd unit.'], 'verified', ['infrastructure', 'uses/arch-linux']),
  topic('homelab/docker-network', 'Docker network', 'Cross-project service discovery on the external homelab bridge.', 'Homelab', 'The external homelab bridge is stated as 172.26.0.0/16. The network-creation command is not in the supplied snapshot, so the subnet is documented from the owner-provided architecture statement.', ['Every active Compose project attaches to homelab.', 'Immich also has a project-default network.', 'Homepage also joins immich_default.', 'Internal targets use container DNS names.'], 'verified', ['homelab/container-communication', 'decisions/single-shared-network'], network),
  topic('homelab/cloudflare-tunnel', 'Cloudflare Tunnel', 'Outbound ingress from Cloudflare hostnames to loopback-published container ports.', 'Homelab', 'A native cloudflared process reads the ingress map and forwards each hostname to 127.0.0.1. This is routing evidence, not proof that a Cloudflare Access application protects a hostname.', ['No router port-forwarding is described.', 'No Nginx, Caddy, or Traefik reverse proxy is present.', 'The final ingress rule returns HTTP 404.', 'Access policies are configured outside this file and remain unverified.'], 'verified', ['homelab/domain-map', 'decisions/cloudflare-tunnel-over-reverse-proxy']),
  {
    slug: 'homelab/domain-map', title: 'Domain map', description: 'Verified Cloudflare Tunnel hostnames and loopback origins.', section: 'Homelab', provenance: 'verified', intro: 'The current tunnel configuration maps hostnames directly to host loopback ports. Application authorization is shown as inferred or unverified rather than asserted.',
    facts: [['code.sampreetpatil.com', '127.0.0.1:8080 · service definition absent'], ['public.sampreetpatil.com', '127.0.0.1:8081 · service definition absent'], ['dev.sampreetpatil.com', '127.0.0.1:8787 · service definition absent'], ['music.sampreetpatil.com', 'Navidrome · 4533'], ['photos.sampreetpatil.com', 'Immich · 2283'], ['dash.sampreetpatil.com', 'Homepage · 3000'], ['pdf.sampreetpatil.com', 'Stirling PDF · 8082→8080'], ['jellyfin.sampreetpatil.com', 'Jellyfin · 8096'], ['qb.sampreetpatil.com', 'qBittorrent · 8083→8080'], ['prowlarr.sampreetpatil.com', 'Prowlarr · 9696'], ['tv.sampreetpatil.com', 'Sonarr · 8989'], ['movies.sampreetpatil.com', 'Radarr · 7878'], ['kuma.sampreetpatil.com', 'Uptime Kuma · 3001'], ['grafana.sampreetpatil.com', 'Grafana · 3002→3000'], ['prometheus.sampreetpatil.com', 'Prometheus · 9090'], ['alerts.sampreetpatil.com', 'Alertmanager · 9093'], ['loki.sampreetpatil.com', 'Loki · 3100'], ['blackbox.sampreetpatil.com', 'Blackbox Exporter · 9115'], ['portainer.sampreetpatil.com', 'Portainer · 9000'], ['logs.sampreetpatil.com', 'Dozzle · 8088→8080']],
    sections: [{ title: 'Interpretation', body: 'A tunnel route proves reachability configuration only. It does not prove that the service is currently online or protected by a Cloudflare Access policy.', items: ['Prometheus, Loki, Blackbox Exporter, Alertmanager, and Dozzle require special attention because upstream defaults do not provide an identity-aware login.', 'The tunnel UUID and credentials path are deliberately omitted.'] }], related: ['homelab/cloudflare-tunnel', 'homelab/security-model']
  },
  topic('homelab/container-communication', 'Container communication', 'DNS-based east-west calls across the shared bridge.', 'Homelab', 'Containers never use localhost to reach other containers. Localhost inside a container refers to that same container, so inter-service calls use names such as prometheus, loki, sonarr, and qbittorrent.', ['Prometheus reaches exporters by container DNS.', 'Alloy writes to http://loki:3100.', 'Sonarr and Radarr integrate with qBittorrent by service name.', 'Homepage reads application APIs across Docker networks.'], 'verified', ['homelab/docker-network', 'homelab/service-dependency-graph']),
  topic('homelab/service-dependency-graph', 'Service dependency graph', 'The principal runtime dependencies across applications, data, and observability.', 'Homelab', 'The graph focuses on meaningful application dependencies rather than drawing every monitoring edge.', ['Immich depends on PostgreSQL and Valkey.', 'Grafana depends on Prometheus and Loki.', 'Prometheus depends on exporters and Alertmanager.', 'Jellyfin consumes media imported by the automation pipeline.'], 'verified', ['homelab/services', 'homelab/architecture'], media),
  topic('homelab/monitoring-stack', 'Monitoring stack', 'Metrics collection, black-box probing, visualization, and alert routing.', 'Homelab', 'Prometheus is configured for 15-second scrapes. Node Exporter covers the host, cAdvisor covers containers, and Blackbox Exporter covers HTTP reachability.', ['HostDown after 30 seconds', 'ServiceDown after one minute', 'CPU >85% for five minutes', 'Memory >90% for five minutes', 'Root disk <15% free for five minutes', 'Container restart activity'], 'verified', ['homelab/services/prometheus', 'homelab/services/alertmanager'], monitoring),
  topic('homelab/logging-stack', 'Logging stack', 'Docker, journal, and custom operations logs collected by Alloy and retained in Loki.', 'Homelab', 'Alloy attaches host, job, container, Compose project, Compose service, image, and stream labels before forwarding logs to the local Loki endpoint.', ['Docker discovery refreshes every five seconds.', 'Journald collection starts with a 24-hour max age.', 'docker-events.log and docker-cleanup.log are tailed as operation sources.', 'Loki retention is 48 hours.'], 'verified', ['homelab/services/alloy', 'homelab/services/loki'], logging),
  topic('homelab/media-stack', 'Media stack', 'Indexer, manager, download client, libraries, and playback server.', 'Homelab', 'Prowlarr centralizes indexers; Sonarr and Radarr coordinate requested content; qBittorrent writes downloads; Jellyfin reads the imported libraries.', ['Downloads and library paths should share a filesystem for hardlinks or atomic moves.', 'Application API keys are private.', 'Jellyfin hardware transcoding is not configured.'], 'verified', ['homelab/services/jellyfin', 'homelab/services/qbittorrent'], media),
  topic('homelab/photo-stack', 'Photo stack', 'Immich, Valkey, PostgreSQL, and filesystem asset storage.', 'Homelab', 'The active Compose file includes the server, queue/cache, and database. Machine learning is commented out and must not be described as active.', ['Assets live under ${UPLOAD_LOCATION}.', 'Database files live under ${DB_DATA_LOCATION}.', 'The database uses checksums.', 'Machine-learning model cache is not active.'], 'verified', ['homelab/services/immich', 'homelab/services/postgresql'], photo),
  topic('homelab/music-stack', 'Music stack', 'A read-only FLAC library served by Navidrome.', 'Homelab', 'Navidrome maintains its own application database while the source music directory is mounted read-only.', ['Hourly library scans', '48-hour session timeout', 'Subsonic-compatible clients', 'Independent lifecycle from Jellyfin'], 'verified', ['homelab/services/navidrome', 'uses/software'], music),
  topic('homelab/automation-stack', 'Automation stack', 'Media imports, update notifications, cleanup, and event recording.', 'Homelab', 'Automation is intentionally split by responsibility: Servarr manages libraries, Diun reports updates, and custom scripts record events or reclaim unused Docker objects.', ['Diun checks every six hours.', 'Diun reports changes but does not deploy them.', 'docker-cleanup.sh uses targeted prune commands.', 'Script schedules are not in the supplied evidence.'], 'verified', ['homelab/custom-scripts', 'homelab/services/diun']),
  topic('homelab/storage-layout', 'Storage layout', 'Persistent configuration, databases, media, observability data, and logs.', 'Homelab', 'State spans project-local directories under /home/sam/homelab and selected operational paths under /home/sam/docker-data.', ['Media: /home/sam/homelab/media', 'Selected application configs: project-local ./config', 'Operational service data: /home/sam/docker-data', 'Monitoring data: monitoring/data', 'Private environment files are excluded from publication.'], 'verified', ['homelab/filesystem-layout', 'homelab/backup-strategy']),
  topic('homelab/filesystem-layout', 'Filesystem layout', 'The intended separation between configuration, durable data, cache, logs, and media.', 'Homelab', 'The published view describes responsibilities without copying runtime databases, cache directories, media, logs, or credentials into the portfolio repository.', ['Compose and safe configs are source evidence.', 'Databases and WAL files are runtime state.', 'Caches and generated thumbnails are rebuildable where documented.', 'Media and database backups require different consistency rules.'], 'verified', ['homelab/storage-layout', 'homelab/recovery-strategy']),
  topic('homelab/backup-strategy', 'Backup strategy', 'A proposed tiered backup design for configuration, databases, and irreplaceable assets.', 'Homelab', 'No backup job was supplied, so this page is a target operating model rather than a claim of protection.', ['Tier 1: encrypted off-host copies of photos and irreplaceable media.', 'Tier 2: PostgreSQL dumps plus Immich assets from a coordinated point.', 'Tier 3: Compose, sanitized configs, Grafana provisioning, and application databases.', 'Caches, downloads in progress, and short-retention logs can be rebuilt.'], 'proposed', ['homelab/recovery-strategy', 'homelab/storage-layout']),
  topic('homelab/recovery-strategy', 'Recovery strategy', 'A dependency-ordered restore runbook for the single-host estate.', 'Homelab', 'Recovery starts with the host, Docker, networks, and filesystem ownership before restoring data services and applications.', ['Recreate host and homelab network.', 'Restore PostgreSQL and Immich assets together.', 'Restore application configs before media servers.', 'Start observability after core services so it can validate recovery.', 'Run application-level smoke tests and record recovery time.'], 'proposed', ['homelab/backup-strategy', 'homelab/operations']),
  topic('homelab/operations', 'Operations', 'Repeatable checks for updates, incidents, capacity, and controlled changes.', 'Homelab', 'Compose files are the deployment record. Portainer and Dozzle assist inspection, while durable changes should return to configuration.', ['Review Diun notifications before upgrades.', 'Capture current container health and disk capacity.', 'Back up state before schema-changing upgrades.', 'Validate logs, metrics, and public routes after change.'], 'inferred', ['homelab/custom-scripts', 'homelab/performance']),
  topic('homelab/custom-scripts', 'Custom scripts', 'Structured Docker event logging and targeted cleanup operations.', 'Homelab', 'docker-events.sh converts selected lifecycle actions to compact JSON. docker-cleanup.sh prunes stopped containers, dangling images, unused networks, and builder cache while logging output.', ['Event actions: create, start, stop, die, destroy, kill.', 'Warnings: die, kill, and destroy.', 'Cleanup intentionally does not run docker system prune --volumes.', 'The systemd unit or timer definitions are absent.'], 'verified', ['homelab/logging-stack', 'homelab/automation-stack']),
  topic('homelab/security-model', 'Security model', 'Trust boundaries, public exposure, container capabilities, secrets, and proposed hardening.', 'Homelab', 'Cloudflare Tunnel reduces inbound network exposure but does not replace authentication. Application defaults and Cloudflare Access policies are separate controls.', ['Never publish API keys, webhooks, passwords, salts, or database state.', 'Remove public observability APIs or enforce Access.', 'Treat Docker socket access as high privilege.', 'Prefer read-only mounts where write access is unnecessary.', 'Pin images and stage upgrades.'], 'inferred', ['homelab/cloudflare-tunnel', 'infrastructure/security']),
  topic('homelab/performance', 'Performance', 'CPU, memory, disk I/O, network, and contention points on the single host.', 'Homelab', 'The largest burst workloads are media transcoding, Immich asset processing, torrent I/O, library scans, and observability queries.', ['Prefer direct play in Jellyfin.', 'Keep PostgreSQL on local SSD storage.', 'Watch download and import contention.', 'Keep Loki label cardinality bounded.', 'Add limits only after measurement identifies contention.'], 'inferred', ['homelab/monitoring-stack', 'homelab/storage-layout']),
  topic('homelab/roadmap', 'Roadmap', 'Evidence-driven improvements ordered by security and recoverability.', 'Homelab', 'The roadmap prioritizes protecting public management endpoints and proving recovery before adding orchestration complexity.', ['Rotate exposed credentials and externalize secrets.', 'Correct Prometheus mounts and persist the TSDB.', 'Implement and test backups.', 'Protect or remove public observability endpoints.', 'Pin high-impact images.', 'Add configuration validation and controlled update runbooks.'], 'proposed', ['homelab/security-model', 'homelab/backup-strategy']),
  topic('homelab/services', 'Service catalog', 'Every deployed service, container image, hostname, dependency, and operational role.', 'Homelab', 'The catalog is generated from the typed service registry and links to a complete page for every documented service.', ['Browse by category.', 'Search by service, container, hostname, or dependency.', 'Use provenance labels to distinguish facts from inference.'], 'verified', []),

  topic('development', 'Development', 'Languages, frameworks, systems work, AI/ML, security, and delivery practices evidenced by the portfolio.', 'Development', 'This section describes demonstrated work rather than turning every dependency into an expertise claim.', ['Backend and API engineering', 'Applied AI and machine learning', 'Systems and CLI development', 'Web and mobile application development', 'Security-oriented projects'], 'inferred', ['development/languages', 'development/workflow']),
  topic('development/languages', 'Languages', 'A practical language portfolio organized by demonstrated use.', 'Development', 'Python, JavaScript/TypeScript, Rust, Dart, Java, C++, SQL, and introductory Go appear across projects and stated skills.', ['Python: backend, data, ML, automation', 'JavaScript/TypeScript: React and Next.js', 'Rust: systems tools and CLI packages', 'Dart: Flutter applications', 'SQL: application data work', 'Go: familiar rather than primary'], 'inferred', ['development/frameworks', 'development/backend']),
  topic('development/frameworks', 'Frameworks', 'Framework choices tied to project shapes rather than popularity.', 'Development', 'FastAPI and Flask support Python services; React and Next.js support web interfaces; Flutter supports mobile applications.', ['FastAPI for typed async APIs', 'Next.js and React for web applications', 'Flutter for cross-platform mobile clients', 'PyTorch and TensorFlow for model work'], 'inferred', ['development/backend', 'development/ai-ml']),
  topic('development/backend', 'Backend engineering', 'API boundaries, modular services, validation, asynchronous work, and operational visibility.', 'Development', 'Backend work is centered on Python APIs, service separation, structured data, and integrations that can be tested independently.', ['FastAPI feature modules', 'Explicit configuration boundaries', 'Typed request and response models', 'Background processing for expensive work', 'Metrics and logs as design concerns'], 'inferred', ['development/workflow', 'development/security']),
  topic('development/ai-ml', 'AI and machine learning', 'Applied evaluation, retrieval, computer vision, and model-backed product work.', 'Development', 'Portfolio evidence includes multimodal evaluation, adaptive learning, research copilots, GraphRAG, YOLO-based detection, inpainting, and natural-language data analysis.', ['PyTorch and TensorFlow', 'RAG and GraphRAG', 'LangChain and LLM APIs', 'Pandas, NumPy, and scikit-learn', 'OpenCV and object tracking'], 'inferred', ['development/backend', 'development/security']),
  topic('development/security', 'Security engineering', 'Threat-aware backend design and explicit trust boundaries.', 'Development', 'Security work is represented by an OWASP scanner project, SSH writing, homelab exposure decisions, and careful secret boundaries.', ['Authentication and authorization', 'Input validation and SSRF boundaries', 'Secret handling', 'Container and network privilege', 'Observability without sensitive-data leakage'], 'inferred', ['infrastructure/security', 'homelab/security-model']),
  topic('development/tooling', 'Development tooling', 'Git, Docker, notebooks, package tooling, databases, and cloud platforms used across projects.', 'Development', 'Tools are documented by role and evidence, not as an undifferentiated logo wall.', ['Git for source history', 'Docker and Compose for reproducible services', 'Jupyter for experiments', 'Firebase and vector databases where projects require them', 'AWS familiarity from project work'], 'inferred', ['development/editor', 'development/workflow']),
  topic('development/editor', 'Editor setup', 'A keyboard-first terminal workflow centered on Vim and Alacritty.', 'Development', 'The exact plugin list is not supplied, so this page documents the operating philosophy rather than inventing dotfiles.', ['Vim modal editing', 'Alacritty terminal', 'Shell-native Git and Docker workflows', 'Configuration kept understandable before automation'], 'inferred', ['uses/vim-alacritty', 'development/workflow']),
  topic('development/linux', 'Linux development', 'Linux as both workstation environment and infrastructure substrate.', 'Development', 'Arch Linux, i3, Hyprland, systemd, shell scripting, SSH, and Docker connect development practice to operations.', ['Package and service ownership', 'systemd units and journals', 'Filesystem permissions', 'Networking and SSH', 'Shell automation'], 'inferred', ['uses/arch-linux', 'infrastructure']),
  topic('development/docker', 'Docker development', 'Compose-based local and server workflows with explicit storage and networking.', 'Development', 'Containers package services, while Compose records their images, ports, mounts, dependencies, and networks.', ['One service responsibility per container where practical', 'Persistent state outside writable layers', 'Internal DNS for service calls', 'Health checks and logs as first-class configuration'], 'verified', ['infrastructure/docker', 'decisions/compose-over-kubernetes']),
  topic('development/cloud', 'Cloud', 'Cloudflare deployment and familiarity with AWS and managed application services.', 'Development', 'The portfolio itself deploys through OpenNext on Cloudflare Workers; the homelab uses Cloudflare DNS and Tunnel.', ['Cloudflare Workers and OpenNext', 'Cloudflare DNS and Tunnel', 'AWS listed as project tooling', 'Firebase for selected application backends'], 'inferred', ['infrastructure/cloudflare', 'development/tooling']),
  topic('development/workflow', 'Development workflow', 'A proposed, evidence-aligned loop for building and operating maintainable software.', 'Development', 'The workflow favors readable modules, typed interfaces, small reversible changes, tests, builds, documentation, and production diagnostics.', ['Understand before automating.', 'Keep secrets outside source.', 'Test behavior at boundaries.', 'Build before deployment.', 'Document decisions and recovery paths.'], 'inferred', ['development/tooling', 'decisions']),

  topic('infrastructure', 'Infrastructure', 'The reusable engineering patterns behind the personal cloud.', 'Infrastructure', 'These pages summarize cross-cutting capabilities and link back to the detailed homelab evidence.', ['Ingress', 'Container runtime', 'Metrics and logs', 'Security boundaries', 'Automation and recovery'], 'verified', ['infrastructure/cloudflare', 'infrastructure/observability']),
  topic('infrastructure/cloudflare', 'Cloudflare', 'Edge DNS, Tunnel ingress, Workers deployment, and identity-aware hardening opportunities.', 'Infrastructure', 'Cloudflare serves two different roles: the portfolio runs on Workers through OpenNext, while the homelab uses DNS and Tunnel.', ['Outbound tunnel connections', 'Hostname-to-origin routing', 'TLS at the Cloudflare edge', 'Access as a separate optional policy layer'], 'verified', ['homelab/cloudflare-tunnel', 'development/cloud']),
  topic('infrastructure/docker', 'Docker infrastructure', 'Runtime packaging, Compose ownership, networks, mounts, and daemon trust.', 'Infrastructure', 'Docker is an implementation mechanism, not the architecture itself. The durable design is the relationship between services, data, and operational controls.', ['Independent Compose projects', 'External shared bridge', 'Bind-mounted persistent data', 'Docker socket consumers', 'Deliberate image updates'], 'verified', ['homelab/services/docker', 'homelab/docker-network']),
  topic('infrastructure/monitoring', 'Monitoring', 'Signals that answer whether the host and services are functioning.', 'Infrastructure', 'Metrics and endpoint probes complement one another: exporters report internal state while Blackbox probes report observable reachability.', ['Host resource metrics', 'Container resource metrics', 'HTTP success probes', 'Threshold and reachability alerts'], 'verified', ['homelab/monitoring-stack', 'infrastructure/observability']),
  topic('infrastructure/observability', 'Observability', 'Metrics, logs, event records, visualization, and alert delivery as one operating loop.', 'Infrastructure', 'Prometheus, Loki, Alloy, Grafana, Alertmanager, and exporters form the core loop from signal generation to diagnosis.', ['Collect', 'Label', 'Store', 'Query', 'Visualize', 'Alert'], 'verified', ['homelab/monitoring-stack', 'homelab/logging-stack']),
  topic('infrastructure/security', 'Infrastructure security', 'Layered controls for identities, networks, containers, data, and operational interfaces.', 'Infrastructure', 'A tunnel reduces origin exposure but cannot compensate for an unauthenticated application or a container with excessive privileges.', ['Identity at Cloudflare Access or the application', 'Least-privilege mounts and users', 'Private data services without host ports', 'Secret rotation and externalization', 'Recovery as a security control'], 'inferred', ['homelab/security-model', 'homelab/backup-strategy']),
  topic('infrastructure/automation', 'Infrastructure automation', 'Automation that remains observable, reversible, and scoped.', 'Infrastructure', 'The current estate uses Compose, scheduled update checks, and shell scripts rather than a large configuration-management layer.', ['Diun reports rather than auto-deploys.', 'Cleanup avoids deleting volumes.', 'Docker events are normalized to JSON.', 'Future automation should include validation and recovery checks.'], 'verified', ['homelab/automation-stack', 'homelab/custom-scripts']),

  topic('uses', 'Uses', 'The hardware and software environment used to build and operate the portfolio.', 'Uses', 'Confirmed details are kept separate from representative T480 assumptions and unsupplied dotfile choices.', ['ThinkPad T480', '24 GB RAM', '256 GB SSD', 'Arch Linux', 'i3 and Hyprland', 'Vim and Alacritty'], 'inferred', ['uses/thinkpad-t480', 'uses/arch-linux']),
  topic('uses/thinkpad-t480', 'ThinkPad T480', 'A repairable business laptop used as the primary Linux machine.', 'Uses', 'The machine is confirmed as a ThinkPad T480 with 24 GB RAM and a 256 GB SSD. Intel Core i5-8250U and UHD 620 are documented as a representative assumption, not a verified SKU.', ['Confirmed: ThinkPad T480', 'Confirmed: 24 GB RAM', 'Confirmed: 256 GB SSD', 'Assumed representative CPU: Intel Core i5-8250U', 'Assumed representative graphics: Intel UHD 620'], 'inferred', ['uses/hardware', 'uses/arch-linux']),
  topic('uses/hardware', 'Hardware', 'A compact, upgradeable workstation profile.', 'Uses', 'Only owner-confirmed capacity is asserted. Display, battery size, camera, fingerprint reader, WWAN, keyboard backlight, and discrete graphics vary by T480 SKU and remain unspecified.', ['Two SO-DIMM slots in the T480 platform', 'USB-C and Thunderbolt connectivity are platform capabilities', 'Ethernet and removable storage support fit infrastructure work', 'Optional components are not claimed as installed'], 'inferred', ['uses/thinkpad-t480']),
  topic('uses/arch-linux', 'Arch Linux', 'A transparent rolling Linux environment for learning and daily engineering.', 'Uses', 'Arch exposes the operating system’s moving parts and rewards deliberate maintenance, making it suitable for a first-principles workflow.', ['pacman package management', 'systemd services and journal', 'Explicit desktop composition', 'Current kernels and userland'], 'inferred', ['development/linux', 'decisions/arch-linux-host']),
  topic('uses/i3-hyprland', 'i3 and Hyprland', 'Keyboard-driven tiling environments across X11 and Wayland.', 'Uses', 'Both environments reflect the same preference: predictable workspaces, minimal chrome, and fast keyboard navigation.', ['i3 for mature X11 tiling', 'Hyprland for a modern Wayland workflow', 'Workspace-oriented task separation', 'Configuration rather than heavy desktop defaults'], 'inferred', ['uses/arch-linux', 'uses/vim-alacritty']),
  topic('uses/vim-alacritty', 'Vim and Alacritty', 'A terminal-first editing environment.', 'Uses', 'Vim supplies modal editing and Alacritty supplies a fast terminal surface. Exact plugins and key mappings are not invented without dotfiles.', ['Modal navigation', 'Text-based configuration', 'Shell tools remain directly available', 'Low-latency terminal rendering'], 'inferred', ['development/editor', 'uses/cli-tools']),
  topic('uses/software', 'Software', 'The daily software categories evidenced by the portfolio and infrastructure.', 'Uses', 'The useful inventory centers on function: browser, terminal, editor, Git, containers, API tools, notebooks, and monitoring interfaces.', ['Vim and Alacritty', 'Git and GitHub', 'Docker and Compose', 'Jupyter notebooks', 'Grafana and service administration UIs'], 'inferred', ['uses/cli-tools', 'development/tooling']),
  topic('uses/cli-tools', 'CLI tools', 'Small composable tools for source, systems, networking, and data.', 'Uses', 'The verified scripts use Bash, jq, Docker CLI, and standard Linux utilities. Additional favorites are not asserted without configuration evidence.', ['bash', 'jq', 'docker and docker compose', 'git', 'ssh', 'systemctl and journalctl'], 'verified', ['uses/vim-alacritty', 'homelab/custom-scripts']),

  topic('decisions', 'Decision log', 'Architectural decision records for the infrastructure’s major tradeoffs.', 'Decisions', 'Each record captures context, alternatives, consequences, and conditions that would justify a different choice.', ['13 documented decisions', 'Rationale reconstructed from supplied architecture and owner direction', 'Revisit conditions keep decisions reversible'], 'inferred', [])
];

export const topicBySlug = new Map(topics.map((entry) => [entry.slug, entry]));
